version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "meteor",
    "angularjs"
  ]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"