# Edit
name: Scan Action with ShiftLeft

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --oss-recursive --app shiftleft-js-220411a --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --js --cpg .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - name: Validate Build Rules
      run: ${GITHUB_WORKSPACE}/sl check-analysis --app shiftleft-js-220411a --target tag.branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --source --target tag.branch=master --report
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_GH_PR_REPO_OWNER: ${{ github.repository_owner }}
        SHIFTLEFT_GH_PR_REPO_NAME: ${{ github.event.repository.name }}
       # SHIFTLEFT_GH_PR_NUMBER: ${{github.event.number}}
