name: SonarCloud Security Scan
on:
  pull_request: {}
  push:
    branches:
    - main
    - master
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Send alerts to Telegram
        uses: tjmehta/telegram-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            **SonarCloud Security Scan Results**

            * **Pull Request:** ${{ github.event.pull_request.title }}
            * **Commit:** ${{ github.event.head_commit.id }}
            * **URL:** ${{ github.event.pull_request.html_url }}

            **Security Vulnerabilities Found:**

            ${{ steps.sonarcloud-scan.outputs.sonar_findings }}
